PenguinMod/PenguinMod-ExtensionsGallery

static/extensions/SharkPool/BetterInput.js
=> Fix BetterInput.js

static/extensions/SharkPool/BetterInput.js
I like pissing off the devs with countless better input updates...
Sorry :(
Anyways, this update adds important and cool blocks to the palette:
-Set Gradient Color blocks
-Customizable Shadows
-Better Image Setting (scaling + live updates)
=> Final Better Input (probably)

static/extensions/SharkPool/BetterInput.js
Just Fixes and performance updates from GarboMuffin, pretty important (I think)
=> Update BetterInput.js (GarboMuffin)

static/extensions/Gen1x/better_storage.js
changes the url of the servers to go to the new ones!
=> EMERGENCY SERVERS UPDATE

static/extensions/MikeDev101/cloudlink.js
* Rename extension files
* Increment versions to 0.1.1
* Fix for sending custom commands that resolve in a server "Syntax error".
* Removed useless startHats events.
=> Sync CloudLink with upstream: v0.1.1

static/extensions/SharkPool/Animations.js
Adds new blocks and fixes minor stuff.
=> Minor Update and Patch, Animations extension.

static/extensions/ObviousAlexC/3DMath.js
This is obviousalexC on my alt account. You can tell because me and my alt are both staff in obvious studios. 3d math update
=> QOL proposal update

static/extensions/ObviousAlexC/3DMath.js
My dumba** forgor sprite 1 thing of sprite data I was too focused on triangles
=> Spr data fixed

static/extensions/SharkPool/Animations.js
Added a new Keyframe block for STRETCHING!
=> Update Animations to 1.3

static/extensions/MikeDev101/cloudlink.js
^
This is a critical bugfix that restores functionality for projects that rely upon the username block for obtaining user objects. This also fixes a connection timing bug.
=> Update CloudLink to v0.1.2

static/extensions/ObviousAlexC/PenPlus.js
Backport the V7 depth buffer
Backport tri drawing from V7
Fix colour bug
Fix dot and line drawing bug
=> 6.1 Bugfix patch

static/extensions/SharkPool/Animations.js
Simplifies Code + Adds a "Play animation and wait" block
=> Minor Animations Update

static/extensions/SharkPool/BetterInput.js
=> Update Better Input

static/extensions/SharkPool/Display-Text.js
Adds a new block and fixes minor bugs. Also adds Newline support
=> Update Display Text

static/extensions/SharkPool/Spotify.js
-Replaces Menu and Block Icon
-Fixes Minor Bugs
-Replaces Audio Context to support Penguinmod AND Turbowarp. (I tested it, seems fine)
=> Update Spotify (Garbo Changes)

static/extensions/SharkPool/Sty-Lists.js
-Fixes "Reset All" issues
-Fixes Packager Problem when Rendering Lists with 0 Items
=> Bug Fix Sty-Lists

static/extensions/SharkPool/Sty-Lists.js
=> Another Fucking Sty-Lists Fix Cuz HTML Can't Get Its Shit Together

static/extensions/SharkPool/Recording.js, static/extensions/SharkPool/Speech-Bubbles.js, static/extensions/SharkPool/Sprite-Effects.js
-Code Simplification
-Minor Bug Patches
- New Blend types
- New Advanced Color Map Block
-Bug Fix
=> Update Sprite Effects & Fix Speech Bubbles & Recording

static/extensions/SharkPool/BetterInput.js, static/extensions/SharkPool/Pause-Utilities.js, static/extensions/SharkPool/Sound-Waves.js, static/extensions/SharkPool/Sprite-Effects.js
+ Function Rewrites
+ Brings Back some Legacy Stuff
+ Bug Fixes
- Use 'Push Thread' instead of 'Toggle Script' for Faster Scripts and Less Bugs
- Adds Shockwave
- Fixes Mosaic Bugs
=> Better Input V4 + Update Other Extensions

static/extensions/Ashime/funneimageblocks.js
funne image blocks
idk why i want to add it other than its funne
=> add funny image blocks pls

static/extensions/Box2D
Physics with joints and springs for penguinmod
[example project](https://studio.penguinmod.com/#6201978047161)
=> Create Box2D Physics extension (with joints and springs)

static/extensions/pooiod/Box2D.js
I added controls for physics iterations and performance. I also added a new joint type: Slider
I also propose that the image be updated to this:
=> Update Box2D.js (sliders and performance)

static/extensions/pooiod/Box2D.js
Added a set velocity block, fixed collision groups, and changed "name" to "object".
=> Update Boxed Physics

src/lib/Documentation/BoxedPhysics.md, static/extensions/pooiod/Box2D.js
=> Boxed Physics documentation

src/lib/extensions.js, static/extensions/MubiLop/toastnotifs.js
=> Change credits that were requested by 2digits (themeatly2)

static/extensions/MubiLop/penguingpt.js
https://platform.openai.com/docs/guides/images/language-specific-tips
Example of OpenAI response:
{
"created": 1714088304879,
"data": [{
"url": "AI image url"
}]
}
=> Update PenguinGPT [READY]

static/extensions/MubiLop/penguingpt.js
New features:
> Vision (Make AI see images, only works from gpt-4 and up)
> Claude 3 and LLama support and more models
New blocks:
> Get current model
> Attach image () to next message
=> V1.9 | PenguinGPT Update

static/extensions/Ashime/MoreFields.js
Fix some of the typings for the fi.output, and actually make fi.output work. (more of just internal changes for extensions-of-this-extensions)
=> Field Fixes (More Fields)

static/extensions/PuzzlingGGG/ttsr.js
also sorry for the shit indents i literally just through it in a js beutifier lmao cuz it looked like shit
=> fix ttsr finally

static/extensions/qxsck/big-number.js
High precision operation, support decimals.
=> new extension: Big Number

static/extensions/pooiod/Box2D.js
I fixed a bug where the [Define polygon from costume] block errors when the sprite is hidden, and added some useful math functions
Also added dropdown for [GetBodyAt] block to select dynamic or static bodies
=> Update Box2D.js bugfix and math fuctions

static/extensions/MubiLop/toastnotifs.js
Added HTML Security Updates
Thank you @yri5 for reporting it :3
=> ToastNotifs | Security Update

static/extensions/MubiLop/toastnotifs.js
=> Fix Toast Notifs Alert Error

static/extensions/Ashime/MoreFields.js
Copy of https://github.com/surv-is-a-dev/gallery/commit/e65c5a51eb883d769c7310988d17a8f031f8cfe1
Self explanatory
=> More Fields: Bug fixes

src/lib/extensions.js
it was so corny before :pray::sob:
=> better tts redone description

static/extensions/DogeisCut/BeepBoxPlayer.js
Just a small bugfix for a bug I missed while testing
=> BeepBox Player: Quick Bugfix

static/extensions/pooiod/VideoSharing.js
Updated the show image function to check for "tmp skins" and update the image instead of creating new skins for every image.
also updated the extension security prompt
=> Fix memory leak in VideoSharing

src/lib/extensions.js, static/extensions/MubiLop/toastnotifs.js
Added origin style, deprecated other blocks (hided from palette)
=> Toast Notifs | v1.1

static/extensions/MubiLop/spritesheeter.js
=> Fix Memory Leak | SpriteSheeter

static/extensions/MubiLop/penguingpt.js
=> update penguinai's api url and some other stuff

src/lib/extensions.js, static/images/steve0greatness/timers.svg
Also, added them to the credits.
=> Update extension icon to icon made by Dillon.

static/extensions/Ikelene/googleAuthExtension.js
This should be merged as soon as possible as all current projects using the extension are incompatible with the new API and will not work.
=> Updated googleAuth.js to work with the new API

src/lib/extensions.js, static/extensions/DogeisCut/dogeiscutSet.js, static/images/DogeisCut/dogeiscutSet.svg
=> sets extension

static/extensions/DogeisCut/dogeiscutObject.js
=> Objects: Fix null/undefined not getting parsed from JSON

static/extensions/DogeisCut/dogeiscutObject.js
haha did you know i am the best coder ever hahaha yes
=> Object: fix ReferenceError: item is not defined

static/extensions/DogeisCut/dogeiscutObject.js
=> objects pull request number #9438593869

static/extensions/DogeisCut/dogeiscutObject.js
=> Objects: more optimization

static/extensions/DogeisCut/dogeiscutObject.js
=> Objects: Runtime var support

static/extensions/DogeisCut/dogeiscutObject.js
=> Add set path block

static/extensions/DogeisCut/dogeiscutObject.js
=> Objects: Fix bubble+var bugs

static/extensions/DogeisCut/dogeiscutObject.js
hopefully i didnt break 40 other things cause i made a change to a pretty important function
I tested it and it seems fine....
=> Objects: Fix [object Object] bug with parse block

static/extensions/DogeisCut/dogeiscutObject.js
=> Objects: Fix fromEntries
